### PR TITLE
Add graphic from Paige Losare-Lusby

### PR DESCRIPTION
**Pull request by jhpratt**
cc @yaahc with regard to the license. I opted for [CC BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/), which is a bit more restrictive than we initially discussed. If Paige would prefer something else, feel free to indicate as such.

This is a drawing from Paige Losare-Lusby in August 2022. I was given it and recently digitized it. As the person who created the digital file, I reserve no rights on my end. Paige Losare-Lusby is the sole rights-holder.

### CODE REVIEW

**Comment by Mattsi-Jansky** [comment]
I added this in a last minute addition to the slides for my workshop at Rust Nation UK, with attribution in the bottom-left corner. It looked great! Thanks for the awesome drawing, can see it in use here: https://twitter.com/mattsijansky/status/1626530260958302209/photo/2

**Comment by yaahc** [comment]
She's over the moon seeing that @Mattsi-Jansky, thank you for sharing

**Review by aldeka — APPROVED** [review]

**Comment by aldeka** [comment]
Closing because I'm moving the fan art over to its own page (so this has hella merge conflicts). But I just added the contents of this PR to the site!

**Comment by jhpratt** [comment]
Awesome. Thanks @aldeka!

**Pull request closed without merging**
